name: tool
publish_to: none
environment:
  sdk: '^3.4.0'
dependencies:
  args: ^2.0.0
  charcode: ^1.1.3
  glob: ^2.0.0
  image: ^3.0.0
  markdown: ^7.2.2
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.7.0
  pool: ^1.4.0
  sass: ^1.26.5
  shelf: ^1.0.0
  string_scanner: ^1.0.5
